# Generated by Django 5.2.1 on 2025-05-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0002_carro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
