# Generated by Django 5.2.1 on 2025-05-30 01:24

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renta', '0003_itemcarrito_fecha_fin_itemcarrito_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='fecha_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2025, 5, 30)),
            preserve_default=False,
        ),
    ]
